jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 11.0.3
        os:
        - ubuntu-18.04
        - macOS-latest
        - windows-latest
      max-parallel: 4
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
